/* automatically generated by rust-bindgen 0.64.0 */

pub const SENSOR: u8 = 1;
pub const MAGNET: u8 = 2;
pub const LED: u8 = 3;
pub const HANDSHAKE: u8 = 16;
pub const ACK: u8 = 32;
pub const QUIT: u8 = 255;
#[repr(u32)]
#[non_exhaustive]
#[doc = " @brief\n Enumerates the variants of operations to be worked by the arduino main program."]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum OpKind {
    Sensor = 0,
    Magnet = 1,
    Led = 2,
    Noop = 3,
    Quit = 4,
}
